logging:
  level:
    org.zalando.logbook: TRACE
logbook:
  exclude: /api/v1/auth/**
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://ec2-44-196-174-238.compute-1.amazonaws.com:5432/d5ra9mpj7hag8n
    password: 75bff02421b9f62f0f1a0c5625d9f4e62244861ebc84a9cdbae0585a8863ac84
    username: efyuovdzrdjnuh
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/cutecut_master
  #    username: postgres
  #    password: 3812

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /api/docs
api:
  info:
    title: Review Service API
    description: API to fetch review details for product
    version: 1.0.0
    terms-of-service: http://pdp.com/terms/
    contact:
      name: Review Service API Team
      email: apiteam@example.com
      url: http://pdp.com/team
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: https
    ip: cutecutapp.herokuapp.com #https://cutecutapp.herokuapp.com
    url: boom.uz

jwt:
  secret: gfhg4561967$%#%$%^?>?>:gjhgsdfsd?>jahdqpdsdhgf
  refresh:
    expire: 864000000
  access:
    expire: 9999999999

otp:
  accessKey: 'AccessKey xsTieTlZpZJjxyexNB2LK8PzJ'
  originator: Xurshidbek
  api: https://rest.messagebird.com/messages
  body: 'Your verification code : '
  from: 1000
  bound: 9000
  expiration: 3

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

info:
  contact:
    phone: +998990473164
    email: bekpulatovshoxruh9@gmail.com
    team: CodeX team