logging:
  level:
    org.zalando.logbook: TRACE
logbook:
  exclude: /api/v1/auth/**
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: unicorn2021
    username: postgres
    url: jdbc:postgresql://localhost:5432/cute_cut_app

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /api/docs
api:
  info:
    title: Review Service API
    description: API to fetch review details for product
    version: 1.0.0
    terms-of-service: http://pdp.com/terms/
    contact:
      name: Review Service API Team
      email: apiteam@example.com
      url: http://pdp.com/team
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost:${server.port}
    url: boom.uz

jwt:
  secret: gfhg4561967$%#%$%^?>?>:gjhgsdfsd?>jahdqpdsdhgf
  refresh:
    expire: 864000000
  access:
    expire: 900000000

otp:
  accessKey: 'AccessKey xsTieTlZpZJjxyexNB2LK8PzJ'
  originator: Xurshidbek
  api: https://rest.messagebird.com/messages
  body: 'Your verification code : '
  from: 1000
  bound: 9000
  expiration: 10 #min


info:
  contact:
    phone: +998990473164
    email: bekpulatovshoxruh9@gmail.com
    team: CodeX team

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

